### ISSUE TITLE
Error while the quota is not enough

### ISSUE THREAD

**Issue by zz-bmj** [caicloud/cyclone#154]
When I run `e2e-k8s.sh`, the command-line interface shows me that "All system worker are busy, wait for 10 seconds" and then it gets failed.

**Comment by zz-bmj** [comment]
•INFO[0566] Cyclone receives creating service request     _file_="service.go:111" service_name=cubernetes user_id=aliceUID
[2017-08-24 12:06:53] [INFO] [manager.go:150] watch unfinshed events set: {"event_id":"599e50ddcbb4d26816f7506e","operation":"create-service","service":{"_id":"599e50ddcbb4d26816f7506e","user_id":"aliceUID","name":"cubernetes","username":"alice","description":"A service just for test","repository":{"url":"http://192.168.8.30/bmj/circle-deploy","vcs":"git","status":"accepted"},"jconfig":{},"profile":{},"last_createtime":"2017-08-24T12:06:53.846478159+08:00"},"version":{"create_time":"0001-01-01T00:00:00Z","build_resource":{"memory":0,"cpu":0}},"project":{"create_time":"0001-01-01T00:00:00Z"},"project_version":{"create_time":"0001-01-01T00:00:00Z"},"data":{"Token":""},"worker_info":{"due_time":"0001-01-01T00:00:00Z","used_resource":{"memory":0,"cpu":0}},"status":"pending","worker":{"createTime":"0001-01-01T00:00:00Z","dueTime":"0001-01-01T00:00:00Z"}}

[2017-08-24 12:07:02] [INFO] [event.go:136] create service handler
[2017-08-24 12:07:02] [INFO] [manager.go:422] All system worker are busy, wait for 10 seconds
[2017-08-24 12:07:12] [INFO] [event.go:136] create service handler
[2017-08-24 12:07:13] [INFO] [manager.go:422] All system worker are busy, wait for 10 seconds
[2017-08-24 12:07:23] [INFO] [event.go:136] create service handler
[2017-08-24 12:07:23] [INFO] [manager.go:422] All system worker are busy, wait for 10 seconds
SIGQUIT: quit
PC=0x105c4bb m=0 sigcode=0

goroutine 0 [idle]:
runtime.mach_semaphore_wait(0x200000f03, 0x0, 0x7fff5fbff528, 0x1033aa7, 0xc4202f16c0, 0x393fa40, 0x7fff5fbff530, 0x10568b3, 0xffffffffffffffff, 0x0, ...)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/sys_darwin_amd64.s:415 +0xb
runtime.semasleep1(0xffffffffffffffff, 0x0)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/os_darwin.go:413 +0x4b
runtime.semasleep.func1()
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/os_darwin.go:432 +0x33
runtime.systemstack(0x7fff5fbff558)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/asm_amd64.s:343 +0xab
runtime.semasleep(0xffffffffffffffff, 0x0)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/os_darwin.go:433 +0x4d
runtime.notesleep(0x39400d0)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/lock_sema.go:166 +0xb2
runtime.stopm()
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/proc.go:1650 +0xad
runtime.findrunnable(0xc42001e600, 0x0)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/proc.go:2102 +0x2e4
runtime.schedule()
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/proc.go:2222 +0x14c
runtime.park_m(0xc4202f16c0)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/proc.go:2285 +0xab
runtime.mcall(0x7fff5fbff730)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/asm_amd64.s:269 +0x5b

goroutine 1 [chan receive, 9 minutes]:
testing.(*T).Run(0xc420340f70, 0x2ba9b65, 0xb, 0x2c14810, 0x105c1d5)

**Comment by zz-bmj** [comment]
and the dev cluster shows me that they are no any worker.
![image](https://user-images.githubusercontent.com/29789939/29652021-241c4956-88d6-11e7-877f-6792cbe0520c.png)

**Comment by superxi911** [comment]
You haven't set quota for cloud provider

**Comment by zz-bmj** [comment]
and I try to create service with postman, it returns "success", however, the state is "missing", it can't apply to create a version and just returns that "Repository of service XXX is not healthy, current status missing", I totally don't know what extra happened and how can I fix it.

Lastly, after the quota is expanded, this won't happen again.
I think the cyclone should tell me what's the extra error so that I can fix it quickly, rather than just tell me "All worker is busy" 
And we need to think whether the service can be created successfully in this situation?
And I will make a PR to fix this.
